environment:
  matrix:
    - CONDA_INSTALL_LOCN: C:\Miniconda2-x64
    - CONDA_INSTALL_LOCN: C:\Miniconda3-x64

platform:
    - x64

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda.exe update --yes --quiet conda
  - cmd: set PYTHONUNBUFFERED=1
  - cmd: pip install --upgrade packaging scipy numba pytest
  - cmd: python.exe setup.py install

build: off

test_script:
  - cmd: pytest
