language: python
python:
  - "2.7"
  - "3.4"
install:
  - git --version
  - lsb_release -a
  - sudo apt-get update
  - git --version
  - sudo apt-get upgrade -f -y --force-yes
  - git --version
  - sudo apt-get dist-upgrade -f -y --force-yes
  - git --version
  - python setup.py install
script:
  - py.test
