sudo: false

language: python

python:
  - "2.7"
  - "3.4"

env:
  - CONDA=true
#  - CONDA=false

install:
  - lsb_release -a
  - if [[ "${CONDA}" == "true" ]]; then ./.travis_install.sh; fi
  - if [[ "${CONDA}" == "true" ]]; then source activate test-environment; fi
  - (source activate test-environment && echo "Conda!") || echo "No conda"
  - python --version
  - which python
  - type -a python
  - which py.test
  - type -a py.test
  - echo $PATH
  - ls $HOME/miniconda || echo "No conda"
  - ls $HOME/miniconda/bin || echo "No conda"
  - python setup.py install

script:
  - py.test
