sudo: false

language: python

python:
  - "2.7"
  - "3.4"

env:
  - CONDA=true
  - CONDA=false

install:
  - lsb_release -a
  - if [[ "${CONDA}" == "true" ]]; then
      source auto_version/travis_install_conda.sh numpy scipy numba pip pytest;
    fi
  - python setup.py install

script:
  - py.test
