sudo: false

language: python

python:
  - '2.7'
  - '3.5'

env:
  - CONDA=true
  - CONDA=false

install:
  - lsb_release -a
  - if [[ "${CONDA}" == "true" ]]; then
      source auto_version/travis_install_conda.sh numpy scipy numba pip pytest;
    fi
  - python setup.py install

script:
  - py.test

after_success:
  - chmod +x ./.conda_deploy.sh

deploy:
  matrix:
  - provider: script
    script: "./.conda_deploy.sh"
    skip_cleanup: true
  - provider: pypi
    user: moboyle79
    password:
      secure: SRfvy1ly3R+allSeQncMn4Zc+y6oix6LoabfdkuhTVa0BaSUle+EL+RAOiyZckZ6wQtxn6TQIkXsdbJVRqR2XW75US5UybsDpKXwJOUDse6mJrhwemJxrMjobSrf/IEKBQ5pOj69/phvp/fA3m0fW1FLD5wGkG1l/5HJvH/rTWQ=
