sudo: false

language: python

os:
  - linux
  - osx

python:
  - '2.7'
  - '3.5'

env:
  - CONDA=true
  - CONDA=false

install:
  - lsb_release -a
  - if [[ "${CONDA}" == "true" ]]; then
      PYTHON_VERSION="$TRAVIS_PYTHON_VERSION" CONDA_INSTALLER_OS="$TRAVIS_OS_NAME" source auto_version/travis_install_conda.sh numpy scipy numba pip pytest;
    fi
  - python setup.py install

script:
  - py.test

after_success:
  - chmod +x ./.conda_deploy.sh
  - python ./.meta_yaml_replacer.py

deploy:
  - provider: script
    script: "./.conda_deploy.sh"
    skip_cleanup: true
    on:
      repo: moble/quaternion
      condition: $CONDA = 'true'
      all_branches: true
  - provider: pypi
    user: moboyle79
    password:
      secure: D0OzSdZn5hWjXX5H41g4pnqme1TJaABKGmUpe14PGMaRf8DjisVMZStAsVVWfocxFqQX3gress+KKtxEvdySXxcfkXAp8VTBvZ+V/uzQQFSYmf5KFwTR/yywff7vdCO+eSHztIcdOhz8Uw2poL/f4/BmO9Y5OoHXJPTkvr6MbIk=
    on:
      distributions: sdist bdist_wheel
      repo: moble/quaternion
      python: '3.5'
      condition: $CONDA = 'false'
