sudo: false

language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - CONDA=true
  - CONDA=false

install:
  - lsb_release -a
  - if [[ "${CONDA}" == "true" ]]; then
      ./.travis_conda.sh
    else
      python setup.py install
    fi

script:
  - py.test
