sudo: false

language: python

matrix:
  include:
    - os: linux
      python: '2.7'
      env: CONDA=true
    - os: linux
      python: '2.7'
      env: CONDA=false
    - os: linux
      python: '3.5'
      env: CONDA=true
    - os: linux
      python: '3.5'
      env: CONDA=false
    - os: osx
      language: generic
      env: CONDA=true TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env: CONDA=true TRAVIS_PYTHON_VERSION=3.5

branches:
  except:
    - appveyor

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lsb_release -a ; fi

install:
  - if [[ "${CONDA}" == "true" ]]; then
      PYTHON_VERSION="$TRAVIS_PYTHON_VERSION" CONDA_INSTALLER_OS="${TRAVIS_OS_NAME:-linux}" source auto_version/travis_install_conda.sh numpy scipy numba pip pytest;
    else
      pip install --upgrade -r requirements.txt;
    fi
  - python setup.py install

before_script:
  - rvm get head # https://github.com/travis-ci/travis-ci/issues/6307

script:
  - py.test

after_success:
  - chmod +x ./.conda_deploy.sh
  - python ./.meta_yaml_replacer.py

deploy:
  - provider: script
    script: "./.conda_deploy.sh"
    skip_cleanup: true
    on:
      repo: moble/quaternion
      condition: "$CONDA = 'true'"
  - provider: pypi
    user: moboyle79
    password:
      secure: D0OzSdZn5hWjXX5H41g4pnqme1TJaABKGmUpe14PGMaRf8DjisVMZStAsVVWfocxFqQX3gress+KKtxEvdySXxcfkXAp8VTBvZ+V/uzQQFSYmf5KFwTR/yywff7vdCO+eSHztIcdOhz8Uw2poL/f4/BmO9Y5OoHXJPTkvr6MbIk=
    on:
      distributions: sdist bdist_wheel
      repo: moble/quaternion
      python: '3.5'
      condition: "$CONDA = 'false' && ${TRAVIS_OS_NAME:-linux} = 'linux'"
