sudo: false

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - CONDA=true
  - CONDA=false

install:
  - lsb_release -a
  - [[ "${CONDA}" == "true" ]] && ./.travis_install.sh && source activate test-environment
  - python setup.py install

script:
  - py.test
