sudo: false

language: python

matrix:
  include:
    - os: linux
      python: '2.7'
    - os: linux
      python: '3.6'

branches:
  except:
    - appveyor

before_install:
  -  lsb_release -a

install:
  - pip install --upgrade pip
  - pip install --upgrade packaging scipy numba setuptools
  - git checkout "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
  - git reset --hard "${TRAVIS_COMMIT}"
  - python setup.py install

script:
  - pytest
