sudo: false

language: python

matrix:
  include:
    - os: linux
      python: '2.7'
      env: CONDA=false
    - os: linux
      python: '3.6'
      env: CONDA=false
    - os: linux
      python: '2.7'
      env: CONDA=true
    - os: linux
      python: '3.6'
      env: CONDA=true
    - os: osx
      language: generic
      env: CONDA=true TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env: CONDA=true TRAVIS_PYTHON_VERSION=3.6

branches:
  except:
    - appveyor

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lsb_release -a ; fi

install:
  - if [[ "${CONDA}" == "true" ]]; then
      PYTHON_VERSION="${TRAVIS_PYTHON_VERSION}" CONDA_INSTALLER_OS="${TRAVIS_OS_NAME:-linux}" source auto_version/travis_install_conda.sh numpy scipy numba pip pytest;
    fi
  - if [[ "${CONDA}" == "true" ]]; then conda config --set anaconda_upload yes; fi
  - if [[ "${CONDA}" == "true" ]]; then conda install -n root conda-build anaconda-client; fi
  - pip install packaging
  - git checkout "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
  - git reset --hard "${TRAVIS_COMMIT}"
  - git status
  - git diff
  - git diff-files
  - git diff-index --cached HEAD --
  - python setup.py install

script:
  - py.test

after_success:
  - chmod +x ./.conda_deploy.sh
  - python ./.meta_yaml_replacer.py
  - if [[ "${CONDA}" == "true" ]]; then conda build --token "$ANACONDA_TOKEN" . ; fi

deploy:
  - provider: pypi
    user: moboyle79
    skip_upload_docs: true
    password:
      secure: D0OzSdZn5hWjXX5H41g4pnqme1TJaABKGmUpe14PGMaRf8DjisVMZStAsVVWfocxFqQX3gress+KKtxEvdySXxcfkXAp8VTBvZ+V/uzQQFSYmf5KFwTR/yywff7vdCO+eSHztIcdOhz8Uw2poL/f4/BmO9Y5OoHXJPTkvr6MbIk=
    on:
      distributions: sdist bdist_wheel
      repo: moble/quaternion
      python: '3.6'
      condition: "$CONDA = 'false' && ${TRAVIS_OS_NAME:-linux} = 'linux'"
