sudo: false

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - CONDA=true
  - CONDA=false

install:
  - lsb_release -a
  - if [[ "${CONDA}" == "true" ]]; then
      ./.travis_install.sh
      source activate test-environment
    fi
  - python setup.py install

script:
  - py.test
