sudo: false

language: python

python:
  - "2.7"
  - "3.4"

env:
  - CONDA=true
  - CONDA=false

install:
  - lsb_release -a
  - if [[ "${CONDA}" == "true" ]]; then ./.travis_install.sh; fi
  - if [[ "${CONDA}" == "true" ]]; then export PATH="$HOME/miniconda/bin:$PATH"; fi
  - if [[ "${CONDA}" == "true" ]]; then source activate test-environment; fi
  - python setup.py install

script:
  - py.test
