package:
  name: quaternion
  version: {{ environ.get('package_version', '1.0') }}

source:
  git_url: https://github.com/moble/quaternion.git

build:
  detect_binary_files_with_prefix: true
  script: python setup.py install

requirements:
  build:
    - python {{ python }}
    - numpy >=1.13

  run:
    - python
    - numpy >=1.13

about:
  home: 'https://github.com/moble/quaternion'
  license: MIT
  summary: 'Add built-in support for quaternions to numpy'
